name: Test-CI

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Checkout  
        run: |
          if [ -f .server.lock ]; then
            pkill uvicorn
          fi

          uvicorn package.__main__:app --host 0.0.0.0 --port 8000 &
          touch .server.lock
