name: Test-CI

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Application 
        run: |
          devenv up
