name: Test-CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Application 
        run: |
          devenv up
