name: Test-CI

on:
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          wall Hello Users
          echo Add other actions to build,
          echo test, and deploy your project.
